### ISSUE TITLE
PHP 8.1: Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by ghost** [DariusIII/Zipper#4]
This one is thrown when downloading multiple NZBs as a ZIP:

```
[2022-01-19 19:44:45] REMOVED.ERROR: Invalid or uninitialized Zip object {"userId":12345,"exception":"[object] (ValueError(code: 0): Invalid or uninitialized Zip object at /var/www/REMOVED/vendor/dariusiii/zipper/src/DariusIII/Zipper/Repositories/ZipRepository.php:159)
[stacktrace]
#0 /var/www/REMOVED/vendor/dariusiii/zipper/src/DariusIII/Zipper/Repositories/ZipRepository.php(159): ZipArchive->close()
#1 /var/www/REMOVED/vendor/dariusiii/zipper/src/DariusIII/Zipper/Zipper.php(68): DariusIII\\Zipper\\Repositories\\ZipRepository->close()
#2 /var/www/REMOVED/app/Http/Controllers/GetNzbController.php(113): DariusIII\\Zipper\\Zipper->__destruct()
```

**Comment by DariusIII** [comment]
Looking at the code, i don't see anything that should cause an error. Maybe the archive is broken?

**Comment by ghost** [comment]
Only started after PHP 8.1

**Comment by antoniopaisfernandes** [comment]
Hi,

We've upgraded yesterday from 7.4 to 8.0 and started getting theses errors:

![image](https://user-images.githubusercontent.com/6171197/155314199-438e8a67-4bde-4c5b-bd2f-cfdc54e075d4.png)


Will keep you posted on the search for the solution.

**Comment by ghost** [comment]
@antoniopaisfernandes Switch to https://github.com/stechstudio/laravel-zipstream

**Comment by DariusIII** [comment]
I will check the code as i think i know the cause and will fix it.
